### ISSUE TITLE
Typo in Typography

### ISSUE THREAD

**Issue by gyanl** [websiddu/sketch-material#10]
Typography is spelled as typograhy in the menu. 
<img width="448" alt="screen shot 2017-07-18 at 4 46 05 pm" src="https://user-images.githubusercontent.com/9626697/28314628-f6e139a2-6bd8-11e7-8d20-b11fd23a24dc.png">

Tiny issue, but I thought I'd point it out. Love the plugin!

**Comment by websiddu** [comment]
Fixed 

https://github.com/websiddu/sketch-material/commit/c57e43444c350ed24acd824525b337ecbb52d03b
