### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dMore88** [websiddu/sketch-material#12]
Why not in the future give the chance to generate a custom design system within the plugin  (or a new plugin), i mean, generate the custom "atoms" then save those in the plugin to be called later...that would be awesome :)

**Comment by demersdesigns** [comment]
+1

**Comment by Thoum** [comment]
+1

**Comment by theposch** [comment]
+1

**Comment by sjwoolf** [comment]
+1

**Comment by rvanderson** [comment]
+1

**Comment by websiddu** [comment]
copy of #51
