### ISSUE TITLE
Plugin not available via 3rd Party Installers.

### ISSUE THREAD

**Issue by asiahoe** [websiddu/sketch-material#2]
I can't seem to find your plugin in either Sketchpacks or Sketch Runner. It simply does not appear in the list. I'm using the latest version for all 3 applications.

I've installed the plugin manually for now.

**Comment by websiddu** [comment]
Thanks for the report. 

I have created a PR for sketch plugins repository when they merge this you will be able to see it :) 
https://github.com/sketchplugins/plugin-directory/pull/395

**Comment by websiddu** [comment]
I think it works with Sketch Runner, but not with Sketch Packs. Still working to figure out what the issue is.

**Comment by asiahoe** [comment]
Thank you following up! I was able to find it on Sketch Runner today. 😄

**Comment by websiddu** [comment]
Work with both
![image](https://user-images.githubusercontent.com/968912/28451816-72cbfff8-6da4-11e7-87eb-b83c20c552ed.png)

![image](https://user-images.githubusercontent.com/968912/28451826-805d69ea-6da4-11e7-91ec-96fd65507cf2.png)
