### ISSUE TITLE
Creating a form component (all types) impossible to type the content

### ISSUE THREAD

**Issue by Agrollemund** [websiddu/sketch-material#20]
Hi,

I wanted to test this plugin for quick prototyping and started by using the form > input but when it comes to change the label i can't type.

**Comment by barronlroth** [comment]
Mine types backwards only.

https://www.dropbox.com/s/kqqxy0njwd9lzer/Screenshot%202017-07-20%2010.56.03.png?dl=0

**Comment by websiddu** [comment]
You would need the latest version of both Sketch  and Mac OS 

which is 
Sketch 45 and above 
Mac OS 10.12.5

**Comment by websiddu** [comment]
duplicate of #7
