### ISSUE TITLE
Suggestion: Generate Menus 

### ISSUE THREAD

**Issue by dawitelias** [websiddu/sketch-material#22]
I think the ability to generate menus (like overflow menus) would be super helpful.

Possible config options: 
* number of rows in menu
* content in each row
* row selected state (either tinted text or a left/right aligned checkmark)
* toggle-able row dividers
* disabled text

Great job on the plugin dude. Can't wait to see where this goes!

**Comment by websiddu** [comment]
Added in the latest version.
