### ISSUE TITLE
Demo Request

### ISSUE THREAD

**Issue by PointZeroSeven** [websiddu/sketch-material#23]
This isn't about a bug. It would be great, however, if you could slow down the You Tube video demo so that I could see what's happening. Thanks for a great tool.

**Comment by websiddu** [comment]
You could change the speed of the video sorry for making it too fast :)

![image](https://user-images.githubusercontent.com/968912/28443583-d7d64b76-6d6b-11e7-9fd3-5273eea2c83b.png)
