### ISSUE TITLE
Empty dialogs

### ISSUE THREAD

**Issue by themattdobson** [websiddu/sketch-material#24]
I'm very excited to se this plugin. The demos look awesome.

When I install it whenever I open any feature I get an empty dialog box that won't close. I have to force quit Sketch to start working again. 

Any clue what' happening? 

Is it maybe a firewall issue?

**Comment by websiddu** [comment]
May be?
were you able to https://sketch-material.firebaseapp.com/dialogs access this?

**Comment by themattdobson** [comment]
Yeah. That seems to work fine.

**Comment by websiddu** [comment]
Then you should be able to access the dialog from sketch. What version of sketch are you using?

**Comment by hydra1983** [comment]
Same problem. And I can access the given page.

![image](https://user-images.githubusercontent.com/488235/28812563-d78639a0-76c7-11e7-807c-240b05bdc7d3.png)

**Comment by websiddu** [comment]
What mac os version you are using? I would recommend this 

![image](https://user-images.githubusercontent.com/968912/28997312-327e2736-79c6-11e7-9c5d-b45b1d26cec1.png)
