### ISSUE TITLE
How hard would it be?

### ISSUE THREAD

**Issue by briannhinton** [websiddu/sketch-material#3]
To modify this to use our own designs?

**Comment by websiddu** [comment]
Shouldn't be that hard you just need to tweak the styles and padding etc.

**Comment by swizenfeld** [comment]
Dude if you could building a builder for any style guide like this it would be awesome!! 
the form building alone is amazing

**Comment by websiddu** [comment]
You should also be looking at this https://github.com/airbnb/react-sketchapp
