### ISSUE TITLE
Sketch Material plugin does not work

### ISSUE THREAD

**Issue by tsuuunami** [websiddu/sketch-material#32]
I dl the following plugin

https://websiddu.github.io/sketch-material/?utm_campaign=Sketch%2BNews&utm_medium=email&utm_source=Sketch_News_36

After I click on Generate button, nothing happens. Thoughts?

**Comment by websiddu** [comment]
![image](https://user-images.githubusercontent.com/968912/28944923-47fe0c2a-7859-11e7-984f-96ec36cd203c.png)

**Comment by mywebcompanion** [comment]
Mac 10.12.6 & Sketch 49 . Not working.. No action when i click on plugin items. Any suggestion?

**Comment by tomisml** [comment]
why not working in Sketch 50

any idea why or suggestion ?

**Comment by websiddu** [comment]
Its broken in sketch 50.  I had very less time these days. I will try to fix it soon.

**Comment by tomisml** [comment]
OK 

thank you
