### ISSUE TITLE
closing styles immediately

### ISSUE THREAD

**Issue by dshoukim** [websiddu/sketch-material#35]
would be great to have a checkbox or setting somewhere that allowed me to open the typographic styles quickly, chose a style, and have the dialog close immediately after applying the selected style.

**Comment by websiddu** [comment]
Alternatively you could use the style picker. 

![image](https://user-images.githubusercontent.com/968912/29198545-dc245cc4-7df9-11e7-9a6b-5f43f5e165f5.png)
