### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Annut** [websiddu/sketch-material#36]
Hi there,

First of all what a freaking cool plug-in. Thanks a lot. Here are some future feature requests

**Bottom navigation**
Option to select amount of tabs, show/hide text, choose selected tab

**Tool bar**
- With subtitle
- With avatar
- Transparent
- Select/show icons
<img width="246" alt="screen shot 2017-08-16 at 12 12 09" src="https://user-images.githubusercontent.com/31065395/29358689-2f68cd44-827c-11e7-9adf-7c564bf93f76.png">

Will really saves me time. Thanks in advance.

Annut

**Comment by websiddu** [comment]
Refer to this thread #77
