### ISSUE TITLE
Amazed about the Sketch Material Plugin

### ISSUE THREAD

**Issue by marshallcr** [websiddu/sketch-material#4]
This is awesome!
Just one question before I share this one with my team.
Because of some strange requirement for the brand we work, we're still using Sketch 42, which isn't the latest version.

Installation worked fine.
I made a couple of attempts with the plug in but nothing happened. Assets weren't generated.
I just want to confirm... Is this plugin only working for the latest sketch version?

Thanks again for this great tool.

**Comment by websiddu** [comment]
Yes. This is for sketch 45 and above. There were lot of changes made in the API.
