### ISSUE TITLE
in Forum couldn't find text empty field state

### ISSUE THREAD

**Issue by Raghav789** [websiddu/sketch-material#43]
Awesome plugin thank you, I wish I would've found it sooner, I manually created complex symbol library for all this, anyway for text fields There is one format for filled status and one for error status but none for an empty field. could you please look into it? 

Also while you are adding empty state symbol a small suggestion, duplicate forum filed and symbol remove the 'input value' move the 'label' to the same position (Y=31) that way label stays same when interchanging status.

**Comment by websiddu** [comment]
Generally I use a space to show the empty state.

**Comment by Raghav789** [comment]
I must be missing something, pardon me if I'm wrong but, aren't the these are the three status?
![text](https://user-images.githubusercontent.com/29393153/30238527-74ae297e-9566-11e7-8029-95dc0b264f29.jpg)

**Comment by websiddu** [comment]
So for the 
Empty state this is what I do, enter a blank space in the Label field and blank space in the empty text. 

And selected state is not implemented (sorry) 

Filled text is straight forward :)

**Comment by Raghav789** [comment]
Ok, thank you :)
