### ISSUE TITLE
Place Holder value not being overwritten

### ISSUE THREAD

**Issue by mattcsouza** [websiddu/sketch-material#46]
First off, **fantastic** plug in. THANK YOU!

Secondly, I've noticed with the latest Sketch 47.1 update, under "Forms", the "Place Holder" value is not being replaced with whatever is inputed.

Thanks!

**Comment by ghost** [comment]
+1 Same issue here.

Looks like the structure is kept but not the values you choose from the generator.

**Comment by websiddu** [comment]
Refer to this thread #77
