### ISSUE TITLE
Suggestion: Ability to update style guide of future added components

### ISSUE THREAD

**Issue by mattcsouza** [websiddu/sketch-material#47]
As a user, I want to be able to add a new component, matching the UI specifications (i.e. colors, border radius, etc.) so that I don't have to manually update each individual components added to my document.

**Comment by alexrest** [comment]
I'm not sure if this is what you're asking for... but it would be great to be able to adjust the "sticker sheet" that these material elements come from. This would allow us to use our own (slightly) modified version of the material design kit as our design system. For example, changing the typeface to our own font, or adjusting the color palette. Thanks!

**Comment by alexrest** [comment]
After digging further, if you unzip the .sketchplugin file and go to Contents > Resources, there are 10 .sketch files in there with the "presets" that the plugin uses for creating these UI elements. It seems like I can just modify these .sketch files and call it a day (i'll have to test that). But what if I have multiple designers? I need to be able to collaborate and contribute to the "design system" similar to the new Libraries feature.

**Comment by mattcsouza** [comment]
Yes, that is exactly what I meant... let me know if that works for you! Thanks @alexrest 👍

**Comment by websiddu** [comment]
copy of #51
