### ISSUE TITLE
Crashes on Sketch 48.1

### ISSUE THREAD

**Issue by jshmllr** [websiddu/sketch-material#49]
I don't have any changelog info, but I'm having issues on **Sketch 48.1**.

**Comment by rayshan** [comment]
Same here with tables. On new documents, nothing is inserted. On existing documents (relatively small), Sketch crashes.

**Comment by curious1n** [comment]
+1

**Comment by websiddu** [comment]
Should be fixed in the latest version. Thanks for reporting.

**Comment by rayshan** [comment]
Thanks for the quick response. Just tried 0.1.11, does not seem to be working.

**Comment by websiddu** [comment]
Can you share what exactly now working?

**Comment by websiddu** [comment]
@rayshan  You are correct some times sketch crashes. I'm investigating this :)

**Comment by rayshan** [comment]
If it's still useful, here are the reproduction steps:

- Create new Sketch document
- Create new Desktop HD artboard
- Generate a new table using default options, observe crash

**Comment by websiddu** [comment]
Should be fixed with 0.1.12 let me know if you face any other issues.

**Comment by rayshan** [comment]
Tested table using above steps, inserted correctly without crashing. Thank you so much!

**Comment by palizadeh** [comment]
Color feature crashes. 

- Create new document
- Add Text, write text
- Select Text
- Launch Runner // Select Color //  observe crash.

Cool tool.  Enjoy enjoying using it!

**Comment by websiddu** [comment]
@palizadeh Please update to the latest version 0.1.13. I should have checked thoroughly ;)

**Comment by jshmllr** [comment]
Works great! Closed.
