### ISSUE TITLE
Icons, colors and typography not working

### ISSUE THREAD

**Issue by nakele** [websiddu/sketch-material#50]
When opening the window to pick an icon, color or typography, nothing shows up. The window is empty as in screenshot. Tested on 3 different machines (on the same network)

<img width="1436" alt="screen shot 2017-12-14 at 17 17 33" src="https://user-images.githubusercontent.com/12185661/34005642-7cd076ba-e0f3-11e7-8839-8e99a149b481.png">

Anyone else can try this?

**Comment by wdejelo** [comment]
Same here, all dialog boxes are empty except for chips and table

**Comment by websiddu** [comment]
Ohh.. I was not able to replicate the issue. 

Please try accessing the following URL 

https://sketch-material.firebaseapp.com/dialogs
https://sketch-material.firebaseapp.com/icons

If you don't have problems accessing those URLs, then it should work.

**Comment by nakele** [comment]
I can access both links for both machines. I've also tested different networks, same result. I tried to disable any other plugin but same thing.

Also the mac console doen't show any error from sketch. Do u have any flag or instructions for me to get the output of your plugin and see if there is any error on that side?

Update:
I don't know if it's of any help but I'm on El Capitan, both machines.  I dont have a newer version of OSX. I might update in the future.

 I've inspected the content of the dialog when using "Sketch Materials > Icons . . ." and it seems there are some errors. Have a look at the screenshot. Do you know what they are?
<img width="1314" alt="screen shot 2017-12-18 at 15 19 15" src="https://user-images.githubusercontent.com/12185661/34113274-1bbdb24a-e407-11e7-8964-3280a88c3f18.png">

**Comment by websiddu** [comment]
Ahh that I see, that seems like the problem. 
The older versions of the Macs have the old safari with don't support ES6. I would recommend you to update to the latest version of the Mac. 

Sorry for the inconvience caused.

**Comment by nakele** [comment]
np, good to know that's the case for future reference

**Comment by wdejelo** [comment]
Updated my Mac to High Sierra and things are back to normal! thank you!
