### ISSUE TITLE
FATAL: Bundle not compatible with OS X 10.11 (El Capitan, AppleWebKit/601.7.8)

### ISSUE THREAD

**Issue by maddrag0n** [websiddu/sketch-material#52]
Apparently 601.7.8 does not have support for ES6 language features such as `const`, `let`, etc.

Occurs when selecting `Typography…` from the menu (similar on `Color…` and `Icons…`).

```
[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (vendor.60ca0db67c04e108c261.js:90957)

[Error] TypeError: undefined is not an object (evaluating 'e[n].call')
	r (manifest.c2099ec69162985b5f50.js:1:101)
	(anonymous function) (app.2b7c47d0518cd7018385.js:1:1882)
	r (manifest.c2099ec69162985b5f50.js:1:106)
	webpackJsonp (manifest.c2099ec69162985b5f50.js:1:420)
	global code (app.2b7c47d0518cd7018385.js:1)
```

this is on latest Sketch btw.

**Comment by websiddu** [comment]
Yeah unfortunately the plugin don't work with El Captian, please update your Mac OS. 

Sorry.

**Comment by maddrag0n** [comment]
@websiddu I cannot update my macOS, since it is the latest supported version on my Early 2013 Macbook Pro Retina.

I suggest adding a simple webpack build pipeline with babel, that transform all of that ES6 into cross-browser compatible ES5

**Comment by websiddu** [comment]
Let me check this weekend :)

**Comment by maddrag0n** [comment]
@websiddu let me know if you need a helping hand
