### ISSUE TITLE
Colors don't work in icon panel

### ISSUE THREAD

**Issue by MishaScholte** [websiddu/sketch-material#53]
When I open the icon panel, select the color white and drag the icon onto an artboard, it creates the correct symbol but the fill is black. I would expect it to be white.

See the attachment for a gif. 
![iconpanelbug](https://user-images.githubusercontent.com/6289034/35621922-69f3aeb4-0686-11e8-86cb-e93663ff9387.gif)

**Comment by websiddu** [comment]
Will look into it. Few things are broken in the latest release.

**Comment by ed-jimmy** [comment]
same here, I'm not using any black icons in my designs. So it is very annoying to go back and forth to change the color. Please fix, thanks.

**Comment by websiddu** [comment]
Should be fixed now. Please update to the latest version.
