### ISSUE TITLE
Dialog not working on Sketch v49 (51002)

### ISSUE THREAD

**Issue by josechirivella** [websiddu/sketch-material#54]
Hi There!

Great job btw but recently I updated my Sketch app to the latest version available at the moment which is v49 (51002) and the ability to add dialogs for Mobile and/or Desktop doesn't work.

I can see the file that I'm working on gets modified but the dialog or Layer doesn't appear.

Thanks

**Comment by mnemanja** [comment]
Man I LOVE this plugin :) Great job! Keep it up :)

By the way I can confirm this behaviour.

**Comment by websiddu** [comment]
Should be fixed in the latest version. 
Download it here 

https://github.com/websiddu/sketch-material/raw/master/builds/versions/sketch-material.latest.zip
