### ISSUE TITLE
Some items are not working

### ISSUE THREAD

**Issue by joanapalhares** [websiddu/sketch-material#55]
Hi, I'm using Sketch 49 and some items in the material plugin are not working. When I click on it, it opens an empty dialog window.
They are:
Dialogs, Forms, Menus, and Snackbars.

![print](https://user-images.githubusercontent.com/37216630/37210931-1b1165c8-2389-11e8-96c7-bf442fdb40de.png)

**Comment by websiddu** [comment]
This happens generally 
1. You haven't updated your Mac in a while 
2. You are under a proxy 
3. Your internet connection is lost. 

I doubt the its 1

**Comment by TevynBell** [comment]
Any workaround for the proxy issue? Or is the only solution to not be under a proxy?

**Comment by websiddu** [comment]
Sorry, For now, No. 

Closing this issue for now!
