### ISSUE TITLE
You have exceeded your bandwidth

### ISSUE THREAD

**Issue by stuartwalker559** [websiddu/sketch-material#58]
See attached image. You have a firebase issue.

"Bandwidth Quota Exceeded

This site has exceeded its monthly quota for bandwidth. It must be upgraded via the Firebase console before it can begin serving traffic again."
<img width="442" alt="screen shot 2018-03-27 at 21 30 30" src="https://user-images.githubusercontent.com/13603828/37993446-9f349b82-3206-11e8-8a13-9f4d8942dd60.png">

**Comment by websiddu** [comment]
YES, I'M broke. Do you want to contribute?. ;) 

JK. Fixed it.
