### ISSUE TITLE
Tables not working properly

### ISSUE THREAD

**Issue by throrin19** [websiddu/sketch-material#59]
Hi, I've a problem with table component :

If I remove some options (only with caption and checkboxes), Checkbox Groups are created and Caption is already in generated table.

It's possible to fix that ?

- macOS : 10.13.4
- sketch : 49.3

**Comment by websiddu** [comment]
I'm on vacation past few days. I pushed an update today and it should work now.

Download it here https://github.com/websiddu/sketch-material/raw/master/builds/versions/sketch-material.latest.zip

Thanks a lot for patience.
