### ISSUE TITLE
Sketch v50 and Chips not inserting

### ISSUE THREAD

**Issue by peternowell** [websiddu/sketch-material#61]
Not sure if it's related to updating to Sketch v50 this morning, but the Chips generator doesn't create any layers when I click the pink Generate button. Other plugin options like tables and forms aren't even opening up their GUI window when I click those options in the Plugins menu.

I've been planning to incorporate this plugin into my [Sketch Master](http://sketchmaster.com) courses, as it's a phenomenal resource for Android designers. But these fundamental bugs give me pause. I'd be happy to contribute financially to the plugin's development if that would help. What's required to bring the plugin up to date and fix these bugs?

**Comment by websiddu** [comment]
I'm on vacation past few days. I pushed an update today and it should work now.

Download it here https://github.com/websiddu/sketch-material/raw/master/builds/versions/sketch-material.latest.zip

Thanks a lot for patience.
