### ISSUE TITLE
Doesn't work at all in Sketch 50

### ISSUE THREAD

**Issue by dchadney** [websiddu/sketch-material#63]
Appears in the plugins menu, but nothing happens if I select an item and try to generate or apply.

**Comment by dimonge** [comment]
Am having the same issue, some templates are working, but the table that I needed to use is not working.

**Comment by iconmaster** [comment]
A number of the menu items have no effect, and for those that do "Generate" never inserts any layers.

Sketch v50.2, macOS 10.13.3

**Comment by loracy** [comment]
Me either. does everyone fix the problem after updating the Sketch to v50.2? QAQ

**Comment by timotauchnitz** [comment]
same here: sketch 50.2

**Comment by Nytsee** [comment]
Sketch v 3.3 (11970) nothing seems to be working, nothing happens  !!

**Comment by smarza** [comment]
Doesn't work in sketch 50.2.

**Comment by Nytsee** [comment]
I got it work finally by downgrading sketch to v49 !

**Comment by websiddu** [comment]
Hey folks. I'm on vacation past few days. It should I pushed an update today and it should work now. 

Thanks a lot for patience.
