### ISSUE TITLE
Elevations not working

### ISSUE THREAD

**Issue by shadowlight12** [websiddu/sketch-material#64]
Hello, I've recently encountered an issue that the elevation are not applying (only 2dp). I've disabled all my other plugins and still does not work. My Sketch version is 50.2

**Comment by wdejelo** [comment]
Same problem here, elevation doesn't apply on the latest version.

**Comment by websiddu** [comment]
I'm on vacation past few days. I pushed an update today and it should work now.

Download it here https://github.com/websiddu/sketch-material/raw/master/builds/versions/sketch-material.latest.zip

Thanks a lot for patience.
