### ISSUE TITLE
Button Option Unresponsive

### ISSUE THREAD

**Issue by ghost** [websiddu/sketch-material#65]
Can you update this plugin please?! The button plugin has not been working since the Sketch 50.1 UPDATE!! Please & thanks!

**Comment by websiddu** [comment]
I'm on vacation past few days. I pushed an update today and it should work now.

Download it here https://github.com/websiddu/sketch-material/raw/master/builds/versions/sketch-material.latest.zip

Thanks a lot for patience.

**Comment by ghost** [comment]
It works now! Thank you
