### ISSUE TITLE
The problem with choosing the color of the icons.

### ISSUE THREAD

**Issue by Ahatan65** [websiddu/sketch-material#67]
Icons become almost invisible, only a part of the icon is visible, and its color turns pink, in case of a change to any color except black. 
![image](https://user-images.githubusercontent.com/39758517/40705297-30cb94e2-63f3-11e8-8ae1-5773d40b5222.png)

**Comment by websiddu** [comment]
Does it happen consistently to you? And what version of sketch you are using?

**Comment by Ahatan65** [comment]
Yes. Version 49.3.

30 мая 2018, 13:50:15, от Siddhartha <notifications@github.com>:

Does it happen consistently to you? And what version of sketch you are using?

**Comment by websiddu** [comment]
Please do update sketch to the latest version.
