### ISSUE TITLE
Can't edit the form elements in the generator

### ISSUE THREAD

**Issue by mether** [websiddu/sketch-material#7]
Was playing around with the plugin (looks amazing by the way) and tried to generate some forms, but the inputs don't seem to take my keystrokes. 

I tried it with the Dialog generator and it worked fine, but for some reason I can't edit the input options.

Any thoughts?

Here's a gif of the bug: 

![Here's a gif of the bug](https://user-images.githubusercontent.com/13096366/28300060-35886360-6bc0-11e7-8fe9-1c53c7d93c8e.gif)

The entire time I'm playing with the form fields in this gif I'm pressing my keyboard to see if there are any inputs registered (it keeps playing the Mac OS 'invalid input' sound). It registers the d keystroke when I click the checkbox, and when I create a new text field, but stops straight away afterwards.

Let me know if you need any more info, 
Cheers, Mack

**Comment by websiddu** [comment]
Could you please let me know on what very of Mac OS are you in?

**Comment by mether** [comment]
I'm currently running OS X El Capitan Version 10.11.6. I'm also running Sketch 45.2 (latest)

Here's my user agent if that helps :) 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by websiddu** [comment]
I think thats the problem. Sketch Material uses a  webview to render stuff. I'm really not sure how to fix that issues other than requesting you to update your mac to latest version. :) 
Sorry :|

**Comment by mether** [comment]
Ah fair enough. It's interesting that I only have an issue with the forms, as all other components seem to work fine and let me edit all text and content.

Are the forms potentially more complex than the others? 

Cheers for the reply :)

**Comment by apdex** [comment]
OS 10.12
Latest Sketch
Reinstalled the plugin
Still not able to input text in the forms pop up
Tried to follow your instruction to open in Safari - not able to input text there, but inside Chrome yes
