### ISSUE TITLE
Unable to change Icon Color

### ISSUE THREAD

**Issue by jonathanfilbert** [websiddu/sketch-material#71]
<img width="1440" alt="screen shot 2018-10-03 at 09 00 19" src="https://user-images.githubusercontent.com/30317542/46386296-d8fe6e00-c6ea-11e8-97b2-e4cc8db552c7.png">

I can't seem to overwrite/change the fill color of the icons, is there any fix to it?
For now, I have to export the icon to illustrator, change the fill, then re-import it back to sketch, any fix?

**Comment by websiddu** [comment]
Refer to this thread #77
