### ISSUE TITLE
Sketch 52 compatibility

### ISSUE THREAD

**Issue by jameshyu** [websiddu/sketch-material#72]
Seems like the Generator function is not working in Sketch 52.

**Comment by websiddu** [comment]
Yep. Will be fixed soon.

**Comment by sjwoolf** [comment]
Elevations also do not work since v 52

**Comment by websiddu** [comment]
Sorry everyone, this is taking more time than what I thought. As I had other priorities. I will try to fixit as soon as I get time.

**Comment by websiddu** [comment]
Refer to this thread #77
