### ISSUE TITLE
Does not work completely in the latest Sketch update (52.1)

### ISSUE THREAD

**Issue by kartoziya** [websiddu/sketch-material#73]
Plugin does not work completely in the latest Sketch update (52.1).

**Comment by andypopa** [comment]
Confirmed

**Comment by ghost** [comment]
Hello. The icons do not place as symbols. Even with the latest update.

**Comment by ImperialBebek** [comment]
Duplicate of : https://github.com/websiddu/sketch-material/issues/72

**Comment by websiddu** [comment]
Refer to this thread #77
