### ISSUE TITLE
Incompatible with latest Sketch version 52.5

### ISSUE THREAD

**Issue by tahekai** [websiddu/sketch-material#75]
Hi, 

Your plugin is amazing and I use it daily. Unfortunately since the latest Sketch update (ver 52.2) sketch-material isn't working. When can we expect an update?

**Comment by mischugo** [comment]
Same here :-(

**Comment by ShneorCr** [comment]
Same

**Comment by doanural** [comment]
Same Here 👋

**Comment by websiddu** [comment]
Refer to this thread #77
