### ISSUE TITLE
How do I download old version?

### ISSUE THREAD

**Issue by ly525** [websiddu/sketch-material#78]
I perfer material table component in the plugin, but I install sketch v52.3. So I uninstall it and reinstall sketch v51, and install the plugin, but the table does not appear in the list：
![image](https://user-images.githubusercontent.com/12668546/48455236-48d93b80-e7f5-11e8-9729-65ddbac77032.png)
![image](https://user-images.githubusercontent.com/12668546/48455249-52fb3a00-e7f5-11e8-893d-3c9c0afc1b57.png)

So what do I need to do?How do I download old version，most links I found were 404. Thanks for your great job!

**Comment by chsWeb** [comment]
I also need an older version of the plugin. Maybe someone still has the installer and can share it on dropbox?

**Comment by websiddu** [comment]
here you go. 
https://github.com/8thmouse/sketch-material/raw/master/builds/versions/sketch-material.latest.zip
