### ISSUE TITLE
Cant load the plugin.

### ISSUE THREAD

**Issue by websiddu** [websiddu/sketch-material#79]

**Comment by oribecker** [comment]
Hi

This is what happens 
![screen shot 2018-11-20 at 14 12 11](https://user-images.githubusercontent.com/7923507/48778897-4b90d080-ecce-11e8-8982-0f41d894c72d.png)

**Comment by websiddu** [comment]
No when you open the URL that sent you. @oribecker

**Comment by oribecker** [comment]
Ah sorry @websiddu 
<img width="1440" alt="screen shot 2018-11-20 at 15 39 53" src="https://user-images.githubusercontent.com/7923507/48784417-93b5f000-ecda-11e8-8547-025ec85e0817.png">

**Comment by websiddu** [comment]
Most likely your internet provider is blocking this site. Not sure how I
can resolve this from my side.

Get that site working again you should be able to start using the plug-in.

**Comment by oribecker** [comment]
Thanks!

**Comment by oribecker** [comment]
Hi @websiddu can you please resend me the link I need to make sure works?

**Comment by websiddu** [comment]
https://google-com-sketch-material.firebaseapp.com/m2 @oribecker

**Comment by oribecker** [comment]
Thanks !
