### ISSUE TITLE
Typography did not work on Sketch 49

### ISSUE THREAD

**Issue by hoangtuan151** [websiddu/sketch-material#81]
Dear team,

Firstly I want to say many thanks for your very helpful plugin.

I'm using Sketch 49 and don't know why Typography did not work:

step 1: I add Text object, type something
step 2: select the text object
step 3: open Sketch Material => Typography
step 4: choose an item from list of Typography window, but the text object is not changed

**Comment by websiddu** [comment]
The plugin is not compatible with 49 :(

**Comment by hoangtuan151** [comment]
Thank you!
