### ISSUE TITLE
Where are icons coming from?

### ISSUE THREAD

**Issue by mattfelten** [websiddu/sketch-material#86]
So I'm using your plugin in a project but I can't seem to find a repository of all the SVGs to use on the code side. 

I was hoping https://github.com/google/material-design-icons/ would have the most up to date ones but it hasn't been updated for years and is missing a good chunk of the icons. I also see that http://materialdesignicons.com is missing some too. See `arrow_forward_ios` for instance. There're plenty missing.

I was hoping this project would have all the icons but I'm guessing they're getting loaded from an API somehow. Where are you generating your list of icons from?

**Comment by websiddu** [comment]
The icons are coming an older version. They are currently part of the icons font https://google.github.io/material-design-icons/

**Comment by mattfelten** [comment]
There's no public access to those SVGs though, right? The NPM package is missing a number of them displayed on https://material.io/tools/icons/

**Comment by websiddu** [comment]
Correct.
