### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by elizabethnair** [websiddu/sketch-material#9]
Creating any button caused my sketch to crash. 
Also, I couldn't click any of the fields under forms. Clicking that area just changed the form type. 

Great concept and great work! Thanks so much (:

**Comment by websiddu** [comment]
Do you mind letting me know the version of Mac OS are you using?

**Comment by websiddu** [comment]
duplicate of #7

**Comment by elizabethnair** [comment]
Hi sorry! This went into a sub google folder. I am running on 10.10.5

**Comment by websiddu** [comment]
Please try updating to 10.12.5
