### ISSUE TITLE
Can't update plugin via Sketch 

### ISSUE THREAD

**Issue by rasera** [websiddu/sketch-material#95]
For some reason, I can't update the plugin by clicking the update icon inside Sketch. I am running "Version 62 (91390)" of Sketch.

<img width="477" alt="Screen Shot 2020-02-04 at 11 09 04 AM" src="https://user-images.githubusercontent.com/14168342/73777690-c5c83c00-473e-11ea-94b5-67d41385c48b.png">

**Comment by websiddu** [comment]
This should work now. Thanks for reporting the bug.
